### ISSUE TITLE
导航栏作业反馈

### ISSUE THREAD

**Issue by twhy** [agui526/warriors#2]
如果我来写的话，会让子菜单 `.players` 相对`.teams > li`做绝对定位。这样子菜单就脱离文档流独立定位。你原来的写法子菜单会影响到 content 的内容。一般多级菜单的子菜单都用绝对定位。
```css
.teams > li {
    float: left;
    position: relative;
    transition: all .5s;
}

.players {
    width: 100%;
    position: absolute;
}
```
还有关于重置样式
```css
body, html, nav, div, ul, li, footer {
    margin: 0;
    padding: 0;
    height: 100%;
    width: 100%;
    font-size: 16px;
}
```
只要
```css
body, ul, li {
   margin: 0;
   padding: 0;
}
```
就够了。
最简单粗暴的就是
```css
* { 
  margin: 0;
  padding: 0;
}
```

**Comment by twhy** [comment]
`.content` 高度问题，可以把 `.content`高度去掉，然后
```css
html, body {
    height: 100%;
}

.main {
    height: 100%;
}

body, ul, li {
    margin: 0;
    padding: 0;
}
```
